/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

#define GPIO_PUSH_PULL_TYPE

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
  for(int i = 0; i< 500000 ; i++);
}

int main(void)
{

  GPIO_Handle_t gpio_led;

  gpio_led.pGPIOx = GPIOD;
  gpio_led.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
  gpio_led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;

#ifdef GPIO_PUSH_PULL_TYPE
  gpio_led.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
  gpio_led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
 #else// open drain conf.
  gpio_led.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD;
  // gpio_led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;  // In open Drain Mode we need to either connect Internal or External PUll up Registers, else No voltage would be drive to the output pin and it would be grounded

  // gpio_led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD; // If you want to use external pull up reg. then you need to use this configuration.
  gpio_led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU; // this will use internal pull up registers and led will toggle with less intensity since internal register is in bigger value
#endif

  gpio_led.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

  
  GPIO_PeriClockControl(GPIOD,ENABLE);

  GPIO_Init(&gpio_led);

  while(1)
  {
    GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
    delay();
  }

    /* Loop forever */
//	for(;;);
}
