/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

 #include <stdint.h>
 #include "stm32f407xx.h"
 
 #define GPIO_PUSH_PULL_TYPE
 
 #if !defined(__SOFT_FP__) && defined(__ARM_FP)
 #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
 #endif
 
 void delay(void)
 {
   for (int i = 0; i < 500000 / 2; i++)
     ;
 }
 
 int main(void)
 {
 
   GPIO_Handle_t gpio_led, gpio_button;
 
   gpio_led.pGPIOx = GPIOD;
   gpio_led.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
   gpio_led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
   gpio_led.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
   gpio_led.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
   gpio_led.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; 
   GPIO_PeriClockControl(GPIOD, ENABLE); 
   GPIO_Init(&gpio_led);

   gpio_led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;     //led pin 13
   GPIO_PeriClockControl(GPIOD, ENABLE); 
   GPIO_Init(&gpio_led);

   gpio_led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;     //led pin 14
   GPIO_PeriClockControl(GPIOD, ENABLE); 
   GPIO_Init(&gpio_led);

   gpio_led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;     //led pin 15
   GPIO_PeriClockControl(GPIOD, ENABLE); 
   GPIO_Init(&gpio_led);

 
   // GPIOA Configured for Button  , PIN no 0 connected to button  as per schematic
 
   gpio_button.pGPIOx = GPIOA;
   gpio_button.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
   gpio_button.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
   gpio_button.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
   // gpio_button.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;// in INPUT mode this field doesn't matter
   gpio_button.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
 
   GPIO_PeriClockControl(GPIOA, ENABLE);
 
   GPIO_Init(&gpio_button);
 
   while (1)
   {
     if (GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0) == SET) // switch will go high while pressed in STM32f407 DISC
     {
       // GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12,1);
       delay(); // this delay is to mitigate to pin debouncing else led will not toggle properly
 
       GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);

       GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);

     }
     else
     {
       delay(); // this delay is to mitigate to pin debouncing else led will not toggle properly
 
       GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);

       GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);

     }
   }
 
   /* Loop forever */
   //	for(;;);
 }
 
